"""Chat / agent-interaction endpoints.

The chat endpoint ties the whole backend together:

    1. resolve (or create) the conversation session
    2. run guardrail *pre*-checks on the user input (scope + emergency)
    3. if blocked, return a safe redirect message immediately
    4. build personalized context from memory
    5. run the reasoning workflow (confirm → think → answer → verify)
    6. run guardrail *post*-checks on the generated answer
    7. persist the assistant message and update the session topic
    8. return a structured response (optionally as an SSE stream)
"""

from __future__ import annotations

import json
import logging
from typing import Any, Dict, List

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from agents.guardrails.models import DISCLAIMER_VI

from .deps import Services, get_services, rate_limiter
from .models import (
    ChatHistoryResponse,
    ChatRequest,
    ChatResponse,
    Citation,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["chat"])


def _build_citations(state: Dict[str, Any]) -> List[Citation]:
    """Build structured citations from the workflow state.

    Prefers the full ``retrieved_sources`` objects (title + snippet); falls
    back to the plain citation strings produced by the Answer node.
    """
    citations: List[Citation] = []
    for src in state.get("retrieved_sources") or []:
        if isinstance(src, dict):
            citations.append(
                Citation(
                    source=str(
                        src.get("title") or src.get("source") or "Tài liệu"
                    ),
                    quote=str(src.get("snippet") or ""),
                )
            )
    if not citations:
        for item in state.get("citations") or []:
            text = str(item).strip()
            if text:
                citations.append(Citation(source=text, quote=""))
    return citations


async def _run_chat(request: ChatRequest, svc: Services) -> ChatResponse:
    """Execute the full chat pipeline and return a structured response."""
    # 1. Resolve or create the session.
    session = None
    if request.session_id:
        session = svc.session_manager.get_session(request.session_id)
    if session is None:
        session = svc.session_manager.create_session(user_id=request.user_id)
    session_id = session.id

    # Persist the user's message.
    svc.session_manager.add_message(session_id, "user", request.message)

    # 2 & 3. Guardrail pre-checks (scope + emergency) — short-circuit if blocked.
    pre = svc.guardrail_runner.run_pre_checks(request.message)
    if pre.should_block:
        answer = pre.block_reason or pre.disclaimer or DISCLAIMER_VI
        message_id = svc.session_manager.add_message(
            session_id, "assistant", answer, {"blocked": True, "stage": "pre"}
        )
        logger.info("Chat blocked by pre-checks for session %s", session_id)
        return ChatResponse(
            answer=answer,
            content=answer,
            confidence=0.0,
            citations=[],
            warnings=list(pre.warnings),
            disclaimer=pre.disclaimer or DISCLAIMER_VI,
            reasoning_steps=[],
            session_id=session_id,
            message_id=message_id,
        )

    # 4. Build personalized context from memory (best-effort).
    context: Dict[str, Any] = {}
    try:
        context = svc.context_builder.build_context(request.user_id, session_id)
    except Exception as exc:  # pragma: no cover - defensive
        logger.warning("Context build failed: %s", exc)

    # 5. Run the reasoning workflow.
    state = await svc.reasoning_workflow.run(request.message, context)
    answer = (
        state.get("verified_answer")
        or state.get("formatted_answer")
        or ""
    )
    reasoning_steps = [str(s) for s in (state.get("reasoning_steps") or [])]
    citation_strings = list(state.get("citations") or [])
    warnings: List[str] = list(state.get("warnings") or [])
    confidence = float(state.get("confidence_score", 0.0) or 0.0)

    # 6. Guardrail post-checks (hallucination, safety, confidence).
    # Use actual retrieved document content for grounding checks, NOT
    # citation name strings (e.g. book titles) generated by the LLM.
    # Citation names can never match answer content via token-overlap.
    retrieved_content = [
        src.get("content", src.get("snippet", ""))
        for src in (state.get("retrieved_sources") or [])
        if isinstance(src, dict)
    ]
    post = svc.guardrail_runner.run_post_checks(
        response=answer,
        sources=retrieved_content,
        reasoning=reasoning_steps,
        user_input=request.message,
    )
    if post.should_block:
        answer = post.block_reason or post.disclaimer or answer
    for warning in post.warnings:
        if warning not in warnings:
            warnings.append(warning)
    if post.confidence_score:
        confidence = float(post.confidence_score)
    disclaimer = post.disclaimer or DISCLAIMER_VI

    # 7. Persist the assistant message and update the session topic.
    message_id = svc.session_manager.add_message(
        session_id,
        "assistant",
        answer,
        {
            "confidence": confidence,
            "citations": citation_strings,
            "warnings": warnings,
        },
    )
    try:
        topic = state.get("specialty") or svc.context_builder.detect_topic_from_messages(
            svc.session_manager.get_session_history(session_id)
        )
        if topic:
            svc.session_manager.update_session_topic(session_id, topic)
    except Exception as exc:  # pragma: no cover - defensive
        logger.debug("Topic update skipped: %s", exc)

    # 8. Structured response.
    return ChatResponse(
        answer=answer,
        content=answer,
        confidence=confidence,
        citations=_build_citations(state),
        warnings=warnings,
        disclaimer=disclaimer,
        reasoning_steps=reasoning_steps,
        session_id=session_id,
        message_id=message_id,
    )


def _sse(step: str, content: Any) -> str:
    """Format a single Server-Sent-Event data frame."""
    payload = json.dumps({"step": step, "content": content}, ensure_ascii=False)
    return f"data: {payload}\n\n"


async def _stream_chat(request: ChatRequest, svc: Services):
    """Yield the reasoning stages then the final answer as SSE events."""
    try:
        result = await _run_chat(request, svc)
    except HTTPException:
        raise
    except Exception as exc:  # pragma: no cover - defensive
        logger.exception("Streaming chat failed")
        yield _sse("error", str(exc))
        return

    yield _sse("confirm", {"session_id": result.session_id})
    yield _sse("think", result.reasoning_steps)
    yield _sse(
        "answer",
        {"answer": result.answer, "citations": [c.model_dump() for c in result.citations]},
    )
    yield _sse(
        "verify",
        {"confidence": result.confidence, "warnings": result.warnings},
    )
    yield _sse(
        "done",
        {
            "answer": result.answer,
            "confidence": result.confidence,
            "citations": [c.model_dump() for c in result.citations],
            "warnings": result.warnings,
            "disclaimer": result.disclaimer,
            "reasoning_steps": result.reasoning_steps,
            "session_id": result.session_id,
            "message_id": result.message_id,
        },
    )


@router.post("/chat")
async def chat(request: ChatRequest, svc: Services = Depends(get_services)):
    """Handle a chat turn.

    Returns a JSON :class:`ChatResponse` by default, or an SSE stream when
    ``request.stream`` is true.
    """
    rate_limiter.check(f"chat:{request.user_id or 'anonymous'}")

    if request.stream:
        return StreamingResponse(
            _stream_chat(request, svc),
            media_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
        )

    return await _run_chat(request, svc)


@router.get("/chat/history/{session_id}", response_model=ChatHistoryResponse)
def chat_history(session_id: str, svc: Services = Depends(get_services)):
    """Return the message history and detected topic for a session."""
    session = svc.session_manager.get_session(session_id)
    if session is None:
        raise HTTPException(status_code=404, detail="Session not found")
    return ChatHistoryResponse(messages=session.messages, topic=session.topic)
